name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.0.0

    - name: Download main compilado
      uses: actions/download-artifact@v3
      with:
        name: programa
          
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: margol100
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: margol100/testeci
